#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#list for fibonacci numbers up to 4 million
fibonacci = []
fibonacci_even = []

#fibonacci sequence
i = 1
for i in range(4000000):
    Fn = i-1 + i-2
    fibonacci.append(Fn)
    i +1

#find if even from fibonacci
if Fn in fibonacci:
    a = fibonacci() % 2 == 0
    fibonacci_even.append(a)


#fibonacci_even = (even(fibonacci))
print(fibonacci_even)
